### ISSUE TITLE
data.doc() don't work

### ISSUE THREAD

**Issue by lgertel** [now-ims/fastify-firestore#2]
Hello everyone!
The plugin is working, but I'm not able to call .data on the returned doc.

It works if the reply send all the doc object.
```fastify.get('/users/:id', async (request, reply) => {
    const { id } = request.params;
    console.log(id)
    const docRef = fastify.fs.doc('users/' + id)
    try {
      const doc = await docRef.get()
      
    } catch (e) {
       reply.send(e)
    }
    
    return { doc.data() }
  })

assert.js:663
    throw newErr;
    ^

AssertionError [ERR_ASSERTION]: ifError got unwanted exception: Unexpected token .
    at /Users/lgertel/extreme_solutions/nomikos/node_modules/fastify/fastify.js:305:23
    at Object._encapsulateThreeParam (/Users/lgertel/extreme_solutions/nomikos/node_modules/avvio/boot.js:357:7)
    at Boot.callWithCbOrNextTick (/Users/lgertel/extreme_solutions/nomikos/node_modules/avvio/boot.js:308:5)
    at release (/Users/lgertel/extreme_solutions/nomikos/node_modules/fastq/queue.js:127:16)
    at Object.resume (/Users/lgertel/extreme_solutions/nomikos/node_modules/fastq/queue.js:61:7)
    at Boot.Plugin.loadPlugin.call (/Users/lgertel/extreme_solutions/nomikos/node_modules/avvio/boot.js:150:20)
    at toLoad.finish (/Users/lgertel/extreme_solutions/nomikos/node_modules/avvio/plugin.js:128:7)
    at done (/Users/lgertel/extreme_solutions/nomikos/node_modules/avvio/plugin.js:86:5)
    at check (/Users/lgertel/extreme_solutions/nomikos/node_modules/avvio/plugin.js:97:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    return { doc.data() }

**Comment by puchesjr** [comment]
I'll take a look at this...

**Comment by puchesjr** [comment]
I've corrected the readme example. I apologize for the delay. There was a typo in the `return { doc.data()}` it should be `return { ...doc.data()}` there is a helper function included that will check if the document exists, I have updated the `readme` to show an example using `doc.exists`
